name: Build and Push Updates Course Contents Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        type: choice
        description: 'Docker Image Tag'
        default: 'test'
        options:
          - prod
          - test

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker image
        run: docker build --tag pocket-moodle-updates:update_course_contents .
      
      - name: Save Docker layers cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Deploy
        run: |
          cd /home/aitusa/server_side_configs/
          git pull
          docker-compose -f docker-compose.yml --env-file .env rm -fs ${{ github.event.inputs.docker_tag == 'prod' && '' || github.event.inputs.docker_tag == 'test' && 'test-' }}pocket-moodle-updates-course-contents
          docker-compose -f docker-compose.yml --env-file .env up -d ${{ github.event.inputs.docker_tag == 'prod' && '' || github.event.inputs.docker_tag == 'test' && 'test-' }}pocket-moodle-updates-course-contents

      - name: Send Telegram Notify To IT Chat
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_IT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: 'html'
          message: |
            <b>${{ github.actor }}</b> deployed <b>Pocket Moodle Updates</b>
            Environment: <code>${{ github.event.inputs.docker_tag }}</code>
            Branch: <a href="https://github.com/${{github.repository}}/tree/${{github.ref_name}}">${{github.ref_name}}</a>
            
            <a href="https://github.com/${{github.repository}}/commit/${{github.sha}}/checks/${{github.run_id}}">Workflow run</a>
