name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      docker_tag:
        type: choice
        description: 'Docker Image Tag'
        default: 'test'
        options:
          - test
          - dev-arsen
          - dev-arnur
          - dev-max

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/pocket-moodle-updates:${{ github.event.inputs.docker_tag || github.event_name == 'release' && 'latest' }}

      - name: Send Telegram Notify To Pocket Moodle Chat
        if: github.event_name == 'release'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} released ${{ github.event.release.name }} of Pocket Moodle Updates:

            ${{ github.event.release.body }}

      - name: Send Telegram Notify To IT Chat
        if: github.event_name != 'release'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_IT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} building Pocket Moodle Updates ${{ github.event.inputs.docker_tag }}:

            ${{ github.repositoryUrl }}
